name: Cmake

on:
  workflow_call:

env:
  BUILD_TYPE_RELEASE: Release
  BUILD_TYPE_DEBUG: Debug

  GCC_11: g++-11
  CLANG_14: clang++-14

jobs:
  ubuntu-clang-14-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: sudo apt-get update
      - run: sudo apt-get install -y ${{env.CLANG_14}}
      - run: pip install conan
      - run: conan profile new default --detect
      - run: conan profile update settings.compiler.libcxx=libstdc++11 default
      - run: conan install --build missing -if ${{github.workspace}}/build .
      - run: |
          mkdir -p ${{github.workspace}}/build
          cmake -B ${{github.workspace}}/build -DCMAKE_CXX_COMPILER=/bin/${{env.CLANG_14}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE_RELEASE}}
          cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE_RELEASE}} --target test_mqueue
      - run: ${{github.workspace}}/build/lib/mqueue/bin/test_mqueue

  ubuntu-clang-14-debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: sudo apt-get update
      - run: sudo apt-get install -y ${{env.CLANG_14}}
      - run: pip install conan
      - run: conan profile new default --detect
      - run: conan profile update settings.compiler.libcxx=libstdc++11 default
      - run: conan install --build missing -if ${{github.workspace}}/build .
      - run: |
          mkdir -p ${{github.workspace}}/build
          cmake -B ${{github.workspace}}/build -DCMAKE_CXX_COMPILER=/bin/${{env.CLANG_14}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE_DEBUG}}
          cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE_DEBUG}} --target test_mqueue
      - run: ${{github.workspace}}/build/lib/mqueue/bin/test_mqueue

  ubuntu-gcc-11-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: sudo apt-get update
      - run: sudo apt-get install -y ${{env.GCC_11}}
      - run: pip install conan
      - run: conan profile new default --detect
      - run: conan profile update settings.compiler.libcxx=libstdc++11 default
      - run: conan install --build missing -if ${{github.workspace}}/build .
      - run: |
          mkdir -p ${{github.workspace}}/build
          cmake -B ${{github.workspace}}/build -DCMAKE_CXX_COMPILER=/bin/${{env.GCC_11}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE_RELEASE}}
          cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE_RELEASE}} --target test_mqueue
      - run: ${{github.workspace}}/build/lib/mqueue/bin/test_mqueue

  ubuntu-gcc-11-debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: sudo apt-get update
      - run: sudo apt-get install -y ${{env.GCC_11}}
      - run: pip install conan
      - run: conan profile new default --detect
      - run: conan profile update settings.compiler.libcxx=libstdc++11 default
      - run: conan install --build missing -if ${{github.workspace}}/build .
      - run: |
          mkdir -p ${{github.workspace}}/build
          cmake -B ${{github.workspace}}/build -DCMAKE_CXX_COMPILER=/bin/${{env.GCC_11}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE_DEBUG}}
          cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE_DEBUG}} --target test_mqueue
      - run: ${{github.workspace}}/build/lib/mqueue/bin/test_mqueue

